# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [2]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [8]:
httml = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(httml, sep='\t')

### Step 4. How many products cost more than $10.00?

In [9]:
chipo.item_price = chipo.item_price.str[1:].astype('float')

In [18]:
chipo.query('item_price > 10')['item_price'].count()
#or
len(chipo[chipo['item_price'] > 10])

1130

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [13]:
chipo.pivot_table('item_price', index='item_name').query('item_price > 10')
# wrong approach - ot calculates mean

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>item_price</th>
    </tr>
    <tr>
      <th>item_name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Barbacoa Bowl</th>
      <td>10.187273</td>
    </tr>
    <tr>
      <th>Barbacoa Crispy Tacos</th>
      <td>10.928182</td>
    </tr>
    <tr>
      <th>Barbacoa Salad Bowl</th>
      <td>10.640000</td>
    </tr>
    <tr>
      <th>Barbacoa Soft Tacos</th>
      <td>10.018400</td>
    </tr>
    <tr>
      <th>Bowl</th>
      <td>14.800000</td>
    </tr>
    <tr>
      <th>Carnitas Bowl</th>
      <td>10.833971</td>
    </tr>
    <tr>
      <th>Carnitas Burrito</th>
      <td>10.132712</td>
    </tr>
    <tr>
      <th>Carnitas Crispy Tacos</th>
      <td>11.137143</td>
    </tr>
    <tr>
      <th>Carnitas Salad Bowl</th>
      <td>11.056667</td>
    </tr>
    <tr>
      <th>Chicken Bowl</th>
      <td>10.113953</td>
    </tr>
    <tr>
      <th>Chicken Burrito</th>
      <td>10.082857</td>
    </tr>
    <tr>
      <th>Chicken Crispy Tacos</th>
      <td>10.045319</td>
    </tr>
    <tr>
      <th>Chicken Salad Bowl</th>
      <td>11.170455</td>
    </tr>
    <tr>
      <th>Steak Bowl</th>
      <td>10.711801</td>
    </tr>
    <tr>
      <th>Steak Burrito</th>
      <td>10.465842</td>
    </tr>
    <tr>
      <th>Steak Crispy Tacos</th>
      <td>10.209714</td>
    </tr>
    <tr>
      <th>Steak Salad Bowl</th>
      <td>11.847931</td>
    </tr>
    <tr>
      <th>Veggie Bowl</th>
      <td>10.211647</td>
    </tr>
    <tr>
      <th>Veggie Salad Bowl</th>
      <td>10.138889</td>
    </tr>
    <tr>
      <th>Veggie Soft Tacos</th>
      <td>10.565714</td>
    </tr>
  </tbody>
</table>
</div>

In [21]:
chipo.pivot_table('quantity', index=['item_name', 'item_price']).query('quantity == 1')

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th></th>
      <th>quantity</th>
    </tr>
    <tr>
      <th>item_name</th>
      <th>item_price</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>6 Pack Soft Drink</th>
      <th>6.49</th>
      <td>1</td>
    </tr>
    <tr>
      <th rowspan="6" valign="top">Barbacoa Bowl</th>
      <th>8.69</th>
      <td>1</td>
    </tr>
    <tr>
      <th>8.99</th>
      <td>1</td>
    </tr>
    <tr>
      <th>9.25</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.48</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.49</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.75</th>
      <td>1</td>
    </tr>
    <tr>
      <th rowspan="6" valign="top">Barbacoa Burrito</th>
      <th>8.69</th>
      <td>1</td>
    </tr>
    <tr>
      <th>8.99</th>
      <td>1</td>
    </tr>
    <tr>
      <th>9.25</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.08</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.48</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.75</th>
      <td>1</td>
    </tr>
    <tr>
      <th rowspan="4" valign="top">Barbacoa Crispy Tacos</th>
      <th>8.99</th>
      <td>1</td>
    </tr>
    <tr>
      <th>9.25</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.48</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.75</th>
      <td>1</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Barbacoa Salad Bowl</th>
      <th>9.39</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.89</th>
      <td>1</td>
    </tr>
    <tr>
      <th rowspan="4" valign="top">Barbacoa Soft Tacos</th>
      <th>8.99</th>
      <td>1</td>
    </tr>
    <tr>
      <th>9.25</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.48</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.75</th>
      <td>1</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Bottled Water</th>
      <th>1.09</th>
      <td>1</td>
    </tr>
    <tr>
      <th>1.50</th>
      <td>1</td>
    </tr>
    <tr>
      <th>Bowl</th>
      <th>7.40</th>
      <td>1</td>
    </tr>
    <tr>
      <th>Burrito</th>
      <th>7.40</th>
      <td>1</td>
    </tr>
    <tr>
      <th>Canned Soda</th>
      <th>1.09</th>
      <td>1</td>
    </tr>
    <tr>
      <th>Canned Soft Drink</th>
      <th>1.25</th>
      <td>1</td>
    </tr>
    <tr>
      <th>Carnitas Bowl</th>
      <th>8.99</th>
      <td>1</td>
    </tr>
    <tr>
      <th>...</th>
      <th>...</th>
      <td>...</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">Steak Burrito</th>
      <th>11.08</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.48</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.75</th>
      <td>1</td>
    </tr>
    <tr>
      <th rowspan="4" valign="top">Steak Crispy Tacos</th>
      <th>8.69</th>
      <td>1</td>
    </tr>
    <tr>
      <th>8.99</th>
      <td>1</td>
    </tr>
    <tr>
      <th>9.25</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.75</th>
      <td>1</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Steak Salad</th>
      <th>8.69</th>
      <td>1</td>
    </tr>
    <tr>
      <th>8.99</th>
      <td>1</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Steak Salad Bowl</th>
      <th>9.39</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.89</th>
      <td>1</td>
    </tr>
    <tr>
      <th rowspan="4" valign="top">Steak Soft Tacos</th>
      <th>8.99</th>
      <td>1</td>
    </tr>
    <tr>
      <th>9.25</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.48</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.75</th>
      <td>1</td>
    </tr>
    <tr>
      <th rowspan="4" valign="top">Veggie Bowl</th>
      <th>8.49</th>
      <td>1</td>
    </tr>
    <tr>
      <th>8.75</th>
      <td>1</td>
    </tr>
    <tr>
      <th>10.98</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.25</th>
      <td>1</td>
    </tr>
    <tr>
      <th rowspan="4" valign="top">Veggie Burrito</th>
      <th>8.49</th>
      <td>1</td>
    </tr>
    <tr>
      <th>8.75</th>
      <td>1</td>
    </tr>
    <tr>
      <th>10.98</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.25</th>
      <td>1</td>
    </tr>
    <tr>
      <th>Veggie Crispy Tacos</th>
      <th>8.49</th>
      <td>1</td>
    </tr>
    <tr>
      <th>Veggie Salad</th>
      <th>8.49</th>
      <td>1</td>
    </tr>
    <tr>
      <th rowspan="2" valign="top">Veggie Salad Bowl</th>
      <th>8.75</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.25</th>
      <td>1</td>
    </tr>
    <tr>
      <th rowspan="3" valign="top">Veggie Soft Tacos</th>
      <th>8.49</th>
      <td>1</td>
    </tr>
    <tr>
      <th>8.75</th>
      <td>1</td>
    </tr>
    <tr>
      <th>11.25</th>
      <td>1</td>
    </tr>
  </tbody>
</table>
<p>135 rows × 1 columns</p>
</div>

In [23]:
# Check why one item name has multiple prices:
chipo[chipo.item_name == 'Barbacoa Bowl']
# it seams that one item can have mutliple choice_descriptions and prices as result

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>order_id</th>
      <th>quantity</th>
      <th>item_name</th>
      <th>choice_description</th>
      <th>item_price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>39</th>
      <td>19</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Roasted Chili Corn Salsa, [Fajita Vegetables,...</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>58</th>
      <td>27</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Roasted Chili Corn Salsa, [Fajita Vegetables,...</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>95</th>
      <td>42</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>115</th>
      <td>51</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G...</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>127</th>
      <td>56</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Rice, Pinto Beans...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>136</th>
      <td>61</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Fajita Vegetables...</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>219</th>
      <td>97</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Rice, Black Beans...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>254</th>
      <td>110</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Rice, Cheese, Let...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>418</th>
      <td>182</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>471</th>
      <td>202</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[[Tomatillo-Green Chili Salsa (Medium), Roaste...</td>
      <td>11.48</td>
    </tr>
    <tr>
      <th>592</th>
      <td>244</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Roasted Chili Corn Salsa, [Rice, Cheese, Lett...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>750</th>
      <td>310</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo-Red Chili Salsa (Hot), [Black Beans...</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>803</th>
      <td>330</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo-Red Chili Salsa (Hot), [Black Beans...</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>804</th>
      <td>331</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>840</th>
      <td>346</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Rice, Cheese, Let...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>919</th>
      <td>380</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Fajita Vegetables...</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>1032</th>
      <td>425</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>1068</th>
      <td>440</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Rice, Cheese, Let...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>1174</th>
      <td>483</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo-Green Chili Salsa (Medium), [Black ...</td>
      <td>11.48</td>
    </tr>
    <tr>
      <th>1175</th>
      <td>483</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa (Mild), [Black Beans, Rice...</td>
      <td>11.48</td>
    </tr>
    <tr>
      <th>1179</th>
      <td>485</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[[Roasted Chili Corn Salsa (Medium), Tomatillo...</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>1235</th>
      <td>504</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo-Green Chili Salsa (Medium), [Black ...</td>
      <td>11.48</td>
    </tr>
    <tr>
      <th>1236</th>
      <td>504</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa (Mild), [Black Beans, Rice...</td>
      <td>11.48</td>
    </tr>
    <tr>
      <th>1264</th>
      <td>514</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Rice, Black Beans...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>1347</th>
      <td>550</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa, [Rice, Black Beans, Chees...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>1357</th>
      <td>554</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>1383</th>
      <td>562</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[[Tomatillo-Green Chili Salsa (Medium), Roaste...</td>
      <td>11.48</td>
    </tr>
    <tr>
      <th>1417</th>
      <td>576</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Red Chili Salsa]</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>1419</th>
      <td>576</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Roasted Chili Corn Salsa]</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>1420</th>
      <td>576</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Roasted Chili Corn Salsa]</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>2013</th>
      <td>812</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Black Beans, Chee...</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>2073</th>
      <td>836</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Green Chili Salsa, [Fajita Vegetabl...</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>2253</th>
      <td>907</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>2372</th>
      <td>945</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Rice, Cheese, Let...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>2399</th>
      <td>953</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Roasted Chili Corn Salsa, [Cheese, Lettuce]]</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>2517</th>
      <td>1000</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Roasted Chili Corn Salsa, [Rice, Black Beans,...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>2620</th>
      <td>1041</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>2667</th>
      <td>1059</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Rice, Cheese, Let...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>2749</th>
      <td>1091</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa, [Rice, Black Beans, Chees...</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>2762</th>
      <td>1097</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>2800</th>
      <td>1112</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Rice, Black Beans...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>3017</th>
      <td>1200</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>3025</th>
      <td>1203</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Roasted Chili Corn Salsa, [Fajita Vegetables,...</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>3195</th>
      <td>1278</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato (Mild), [Lettuce, Black Beans, R...</td>
      <td>8.69</td>
    </tr>
    <tr>
      <th>3245</th>
      <td>1299</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-G...</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>3253</th>
      <td>1303</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>3376</th>
      <td>1356</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa, [Rice, Black Beans, Cheese]]</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>3394</th>
      <td>1361</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa, [Rice, Black Beans, Chees...</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>3547</th>
      <td>1426</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>3549</th>
      <td>1426</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa, [Rice, Black Beans, Chees...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>3822</th>
      <td>1533</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato (Mild), [Lettuce, Rice, Cheese]]</td>
      <td>8.69</td>
    </tr>
    <tr>
      <th>4046</th>
      <td>1619</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Green Chili Salsa, [Fajita Vegetabl...</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>4056</th>
      <td>1624</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[[Rice, Cheese]]</td>
      <td>8.69</td>
    </tr>
    <tr>
      <th>4135</th>
      <td>1655</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Roasted Chili Corn Salsa, [Rice, Black Beans,...</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>4140</th>
      <td>1657</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Red Chili Salsa, [Fajita Vegetables...</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>4380</th>
      <td>1748</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>4441</th>
      <td>1770</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Tomatillo Green Chili Salsa, [Rice, Cheese, G...</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>4485</th>
      <td>1786</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>4510</th>
      <td>1793</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Guacamole]</td>
      <td>11.49</td>
    </tr>
    <tr>
      <th>4594</th>
      <td>1825</td>
      <td>1</td>
      <td>Barbacoa Bowl</td>
      <td>[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...</td>
      <td>11.75</td>
    </tr>
  </tbody>
</table>
<p>66 rows × 5 columns</p>
</div>

In [30]:
# Solution provided by exercise
chipo.drop_duplicates(['item_name', 'quantity']).query('quantity == 1')[['item_name', 'item_price']].sort_values('item_price', ascending=False)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>item_name</th>
      <th>item_price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>606</th>
      <td>Steak Salad Bowl</td>
      <td>11.89</td>
    </tr>
    <tr>
      <th>1229</th>
      <td>Barbacoa Salad Bowl</td>
      <td>11.89</td>
    </tr>
    <tr>
      <th>1132</th>
      <td>Carnitas Salad Bowl</td>
      <td>11.89</td>
    </tr>
    <tr>
      <th>7</th>
      <td>Steak Burrito</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>168</th>
      <td>Barbacoa Crispy Tacos</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>39</th>
      <td>Barbacoa Bowl</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>738</th>
      <td>Veggie Soft Tacos</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>186</th>
      <td>Veggie Salad Bowl</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>62</th>
      <td>Veggie Bowl</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>57</th>
      <td>Veggie Burrito</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>250</th>
      <td>Chicken Salad</td>
      <td>10.98</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Chicken Bowl</td>
      <td>10.98</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Steak Soft Tacos</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>554</th>
      <td>Carnitas Crispy Tacos</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>237</th>
      <td>Carnitas Soft Tacos</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>56</th>
      <td>Barbacoa Soft Tacos</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>92</th>
      <td>Steak Crispy Tacos</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>664</th>
      <td>Steak Salad</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>54</th>
      <td>Steak Bowl</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>3750</th>
      <td>Carnitas Salad</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>21</th>
      <td>Barbacoa Burrito</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>27</th>
      <td>Carnitas Burrito</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>33</th>
      <td>Carnitas Bowl</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>11</th>
      <td>Chicken Crispy Tacos</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Chicken Soft Tacos</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>44</th>
      <td>Chicken Salad Bowl</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>1653</th>
      <td>Veggie Crispy Tacos</td>
      <td>8.49</td>
    </tr>
    <tr>
      <th>16</th>
      <td>Chicken Burrito</td>
      <td>8.49</td>
    </tr>
    <tr>
      <th>1694</th>
      <td>Veggie Salad</td>
      <td>8.49</td>
    </tr>
    <tr>
      <th>1414</th>
      <td>Salad</td>
      <td>7.40</td>
    </tr>
    <tr>
      <th>510</th>
      <td>Burrito</td>
      <td>7.40</td>
    </tr>
    <tr>
      <th>520</th>
      <td>Crispy Tacos</td>
      <td>7.40</td>
    </tr>
    <tr>
      <th>673</th>
      <td>Bowl</td>
      <td>7.40</td>
    </tr>
    <tr>
      <th>298</th>
      <td>6 Pack Soft Drink</td>
      <td>6.49</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Chips and Guacamole</td>
      <td>4.45</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Izze</td>
      <td>3.39</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Nantucket Nectar</td>
      <td>3.39</td>
    </tr>
    <tr>
      <th>674</th>
      <td>Chips and Mild Fresh Tomato Salsa</td>
      <td>3.00</td>
    </tr>
    <tr>
      <th>111</th>
      <td>Chips and Tomatillo Red Chili Salsa</td>
      <td>2.95</td>
    </tr>
    <tr>
      <th>233</th>
      <td>Chips and Roasted Chili Corn Salsa</td>
      <td>2.95</td>
    </tr>
    <tr>
      <th>38</th>
      <td>Chips and Tomatillo Green Chili Salsa</td>
      <td>2.95</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Chips and Tomatillo-Green Chili Salsa</td>
      <td>2.39</td>
    </tr>
    <tr>
      <th>300</th>
      <td>Chips and Tomatillo-Red Chili Salsa</td>
      <td>2.39</td>
    </tr>
    <tr>
      <th>191</th>
      <td>Chips and Roasted Chili-Corn Salsa</td>
      <td>2.39</td>
    </tr>
    <tr>
      <th>0</th>
      <td>Chips and Fresh Tomato Salsa</td>
      <td>2.39</td>
    </tr>
    <tr>
      <th>40</th>
      <td>Chips</td>
      <td>2.15</td>
    </tr>
    <tr>
      <th>6</th>
      <td>Side of Chips</td>
      <td>1.69</td>
    </tr>
    <tr>
      <th>263</th>
      <td>Canned Soft Drink</td>
      <td>1.25</td>
    </tr>
    <tr>
      <th>28</th>
      <td>Canned Soda</td>
      <td>1.09</td>
    </tr>
    <tr>
      <th>34</th>
      <td>Bottled Water</td>
      <td>1.09</td>
    </tr>
  </tbody>
</table>
</div>

### Step 6. Sort by the name of the item

In [32]:
chipo.sort_values('item_name')
chipo.drop_duplicates(['item_name', 'quantity']).query('quantity == 1')[['item_name', 'item_price']].sort_values('item_name', ascending=False)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>item_name</th>
      <th>item_price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>738</th>
      <td>Veggie Soft Tacos</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>186</th>
      <td>Veggie Salad Bowl</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>1694</th>
      <td>Veggie Salad</td>
      <td>8.49</td>
    </tr>
    <tr>
      <th>1653</th>
      <td>Veggie Crispy Tacos</td>
      <td>8.49</td>
    </tr>
    <tr>
      <th>57</th>
      <td>Veggie Burrito</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>62</th>
      <td>Veggie Bowl</td>
      <td>11.25</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Steak Soft Tacos</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>606</th>
      <td>Steak Salad Bowl</td>
      <td>11.89</td>
    </tr>
    <tr>
      <th>664</th>
      <td>Steak Salad</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>92</th>
      <td>Steak Crispy Tacos</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>7</th>
      <td>Steak Burrito</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>54</th>
      <td>Steak Bowl</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>6</th>
      <td>Side of Chips</td>
      <td>1.69</td>
    </tr>
    <tr>
      <th>1414</th>
      <td>Salad</td>
      <td>7.40</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Nantucket Nectar</td>
      <td>3.39</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Izze</td>
      <td>3.39</td>
    </tr>
    <tr>
      <th>520</th>
      <td>Crispy Tacos</td>
      <td>7.40</td>
    </tr>
    <tr>
      <th>300</th>
      <td>Chips and Tomatillo-Red Chili Salsa</td>
      <td>2.39</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Chips and Tomatillo-Green Chili Salsa</td>
      <td>2.39</td>
    </tr>
    <tr>
      <th>111</th>
      <td>Chips and Tomatillo Red Chili Salsa</td>
      <td>2.95</td>
    </tr>
    <tr>
      <th>38</th>
      <td>Chips and Tomatillo Green Chili Salsa</td>
      <td>2.95</td>
    </tr>
    <tr>
      <th>191</th>
      <td>Chips and Roasted Chili-Corn Salsa</td>
      <td>2.39</td>
    </tr>
    <tr>
      <th>233</th>
      <td>Chips and Roasted Chili Corn Salsa</td>
      <td>2.95</td>
    </tr>
    <tr>
      <th>674</th>
      <td>Chips and Mild Fresh Tomato Salsa</td>
      <td>3.00</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Chips and Guacamole</td>
      <td>4.45</td>
    </tr>
    <tr>
      <th>0</th>
      <td>Chips and Fresh Tomato Salsa</td>
      <td>2.39</td>
    </tr>
    <tr>
      <th>40</th>
      <td>Chips</td>
      <td>2.15</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Chicken Soft Tacos</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>44</th>
      <td>Chicken Salad Bowl</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>250</th>
      <td>Chicken Salad</td>
      <td>10.98</td>
    </tr>
    <tr>
      <th>11</th>
      <td>Chicken Crispy Tacos</td>
      <td>8.75</td>
    </tr>
    <tr>
      <th>16</th>
      <td>Chicken Burrito</td>
      <td>8.49</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Chicken Bowl</td>
      <td>10.98</td>
    </tr>
    <tr>
      <th>237</th>
      <td>Carnitas Soft Tacos</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>1132</th>
      <td>Carnitas Salad Bowl</td>
      <td>11.89</td>
    </tr>
    <tr>
      <th>3750</th>
      <td>Carnitas Salad</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>554</th>
      <td>Carnitas Crispy Tacos</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>27</th>
      <td>Carnitas Burrito</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>33</th>
      <td>Carnitas Bowl</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>263</th>
      <td>Canned Soft Drink</td>
      <td>1.25</td>
    </tr>
    <tr>
      <th>28</th>
      <td>Canned Soda</td>
      <td>1.09</td>
    </tr>
    <tr>
      <th>510</th>
      <td>Burrito</td>
      <td>7.40</td>
    </tr>
    <tr>
      <th>673</th>
      <td>Bowl</td>
      <td>7.40</td>
    </tr>
    <tr>
      <th>34</th>
      <td>Bottled Water</td>
      <td>1.09</td>
    </tr>
    <tr>
      <th>56</th>
      <td>Barbacoa Soft Tacos</td>
      <td>9.25</td>
    </tr>
    <tr>
      <th>1229</th>
      <td>Barbacoa Salad Bowl</td>
      <td>11.89</td>
    </tr>
    <tr>
      <th>168</th>
      <td>Barbacoa Crispy Tacos</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>21</th>
      <td>Barbacoa Burrito</td>
      <td>8.99</td>
    </tr>
    <tr>
      <th>39</th>
      <td>Barbacoa Bowl</td>
      <td>11.75</td>
    </tr>
    <tr>
      <th>298</th>
      <td>6 Pack Soft Drink</td>
      <td>6.49</td>
    </tr>
  </tbody>
</table>
</div>

### Step 7. What was the quantity of the most expensive item ordered?

In [54]:
list_of_items = chipo.drop_duplicates(['item_name', 'quantity']).query('quantity == 1')[['item_name', 'item_price']]
most_exp_item = list_of_items.sort_values('item_price', ascending=False)[['item_name']].iloc[0][0]
chipo.query('item_name == @most_exp_item').quantity.sum()

31

In [57]:
# different approach. Find the most expensive item and check it's quantity
chipo.sort_values('item_price',ascending=False).head(1)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>order_id</th>
      <th>quantity</th>
      <th>item_name</th>
      <th>choice_description</th>
      <th>item_price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>3598</th>
      <td>1443</td>
      <td>15</td>
      <td>Chips and Fresh Tomato Salsa</td>
      <td>NaN</td>
      <td>44.25</td>
    </tr>
  </tbody>
</table>
</div>

### Step 8. How many times were a Veggie Salad Bowl ordered?

In [64]:
chipo.query('item_name == "Veggie Salad Bowl"')['order_id'].count()

18

### Step 9. How many times people orderd more than one Canned Soda?

In [70]:
chipo.query('item_name== "Canned Soda" & quantity > 1').order_id.count()
# same but slower
len(chipo[(chipo.item_name == "Canned Soda") & (chipo.quantity > 1)])

20